### ISSUE TITLE
invaild code错误应该抛出

### ISSUE THREAD

**Issue by loulin** [Treri/passport-weixin#2]
否则invalid code也会得到一个合法的profile，但没有意义：

``` js
{
  "id": "undefined",
  "provider": "weixin",
  "_raw": "{\"errcode\":41001,\"errmsg\":\"access_token missing\"}",
  "_json": {
    "errcode": 41001,
    "errmsg": "access_token missing"
  }
}
```

问题出在通过code获取access_token，但code错误或超时，参见
1. 授权后接口调用（UnionID）：https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419316518&lang=zh_CN
2. 错误码：https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419316518&lang=zh_CN

**Comment by ik0r** [comment]
:+1:
