### ISSUE TITLE
如果没有绑定公众平台， 不会有 unionid

### ISSUE THREAD

**Issue by spacedragon** [Treri/passport-weixin#9]
如果没有绑定公众平台， 不会有 unionid

这一行
https://github.com/Treri/passport-weixin/blob/master/lib/profile.js#L14
会导致profile.id 总是等于 "undefined"

建议加上
profile.openid = json.openid
profile.id = json.unionid || json.openid

**Comment by faller** [comment]
不会的，我们也没有绑定公众平台，unionid 亲测可用。
如果是公众平台没有绑定开放平台，公众平台拿不到 unionid。
但如果是开放平台没有绑定公众平台，开放平台能拿到 unionid 的，因为 unionid 本来就是属于开放平台的。

**Comment by spacedragon** [comment]
写错了, 是开放平台  ,  我的意思是如果没有 unionid ,  profile.id 就 undefined 了
